name: ChatGPT PR Reviewer

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write  # Ensures write permissions to PRs

jobs:
  review_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: GitHub Actions ChatGPT PR Reviewer
        uses: osl-incubator/github-actions-chatgpt-pr-reviewer@1.0.3
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}  # required
          openai_model: 'gpt-3.5-turbo'  # Use a commonly available model
          openai_temperature: 0.5  # optional
          openai_max_tokens: 2048  # optional
          openai_extra_criteria: |
            - prefer readable variable name instead of short names like `k` and `v`, when apply;
            - verify `SOLID` principles design pattern violations, when apply;
          github_token: ${{ secrets.GITHUB_TOKEN }}  # required
          github_pr_id: ${{ github.event.number }}  # required
