name: ChatGPT PR Reviewer

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: GitHub Actions ChatGPT PR Reviewer
        uses: osl-incubator/github-actions-chatgpt-pr-reviewer@1.0.3
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}  # required
          openai_model: 'gpt-4-1106-preview'  # optional, can be omitted or changed
          openai_temperature: 0.5  # optional, you can adjust the randomness of responses
          openai_max_tokens: 2048  # optional, adjust the length of the response
          openai_extra_criteria: |
            - prefer readable variable name instead of short names like `k` and `v`, when apply;
            - verify `SOLID` principles design pattern violations, when apply;
          github_token: ${{ secrets.GITHUB_TOKEN }}  # required for GitHub actions to access repo
          github_pr_id: ${{ github.event.number }}  # required to get the PR details
